version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pentool-postgres
    environment:
      POSTGRES_DB: pentool
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pentool"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pentool-net

  redis:
    image: redis:7-alpine
    container_name: pentool-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pentool-net

  nats:
    image: nats:2.10-alpine
    container_name: pentool-nats
    command: "--http_port 8222 -js"
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # HTTP monitoring
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pentool-net

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  pentool-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16